### ISSUE TITLE
算起来太慢了 没有实时性啊 

### ISSUE THREAD

**Issue by liuhongyi0101** [noiron/light2d-javascript#1]

**Comment by noiron** [comment]
这里的代码基本上是根据 Milo Yip 这个系列的文章写的，把 C 代码翻译成了 JS 代码，没有进行优化。

[用 C 语言画光（一）：基础](https://zhuanlan.zhihu.com/p/30745861)

**Comment by liuhongyi0101** [comment]
已经很6了
